#' Genera un YAML de ejemplo para declarar indicadores
#'
#' Esta función crea un archivo YAML de ejemplo que actúa como guía/tutorial
#' para declarar indicadores a partir de una base de datos en formato similar
#' a \code{rp_data}. El archivo incluye:
#'
#' - Encabezado general (\code{version}, \code{nombre}, \code{peso}).
#' - Ejemplos de indicadores de tipo:
#'   - \code{tabla_conceptos}
#'   - \code{tabla_compuesta}
#'   - \code{freq_multiple}
#' - Ejemplos de columnas con distintos tipos de cálculo:
#'   - \code{suma}
#'   - \code{conteo_cond}, \code{proporcion_cond}
#'   - \code{proporcion_rel}
#'   - \code{media}, \code{mediana}, \code{minimo}, \code{maximo}
#'   - \code{conteo_cond_fila}, \code{proporcion_sobre_total}
#' - Uso de:
#'   - \code{filas}/\code{grupos} con atajos tipo \code{@total}, \code{@evento}, etc.
#'   - Indicadores compuestos basados en expresiones lógicas (\code{tabla_compuesta}).
#'   - Preguntas de respuesta múltiple dummificadas (\code{freq_multiple} con \code{usar_labels}).
#'   - Banderas precomputadas en \code{rp_data} (e.g. \code{flag_condicion_a}).
#'
#' El objetivo es que el archivo generado sirva como plantilla comentada para
#' que cada usuario pueda adaptarlo a su propio cuestionario y base de datos.
#'
#' @param path Ruta del archivo YAML a generar. Por defecto
#'   \code{"indicadores_ejemplo.yaml"}.
#' @param overwrite Lógico. Si es \code{FALSE} (por defecto) y el archivo ya
#'   existe, la función lanza un error y no sobreescribe el archivo.
#'
#' @return Invisiblemente, la ruta del archivo generado.
#' @export
#'
#' @examples
#' \dontrun{
#' # Generar un YAML de ejemplo en el directorio de trabajo
#' reporte_yaml()
#'
#' # Generar en otra ruta, sobreescribiendo si ya existe
#' reporte_yaml("config_indicadores.yaml", overwrite = TRUE)
#' }
indicadores_yaml <- function(path = "indicadores_ejemplo.yaml",
                         overwrite = FALSE) {

  if (file.exists(path) && !isTRUE(overwrite)) {
    stop(
      "El archivo '", path,
      "' ya existe. Use overwrite = TRUE para sobreescribir.",
      call. = FALSE
    )
  }

  lines <- c(
    "# ===============================================================",
    "# Guía YAML para declarar indicadores a partir de una base de datos",
    "#",
    "# Este archivo es solo un EJEMPLO. La idea es que se copie, renombre",
    "# y adapte a la estructura real de la base (nombres de variables,",
    "# tipos de indicadores, etc.).",
    "#",
    "# Convenciones generales:",
    "# - Se asume que la base principal se llama rp_data.",
    "# - Si existe una variable de pesos (por ejemplo 'peso'), puede",
    "#   declararse en el encabezado. Si no, se ignora.",
    "# - Los comentarios que comienzan con '#' son ignorados por YAML y",
    "#   se usan aquí como documentación.",
    "# ===============================================================",
    "---",
    "version: 1",
    "nombre: \"NOMBRE_DEL_PROYECTO\"   # Nombre libre del set de indicadores",
    "peso: \"peso\"                    # Opcional: nombre de la variable de ponderación en rp_data",
    "",
    "indicadores:",
    "",
    "  # ------------------------------------------------------------",
    "  # EJEMPLO 1: tabla_conceptos con conceptos en filas y columnas derivadas",
    "  # ------------------------------------------------------------",
    "  - id: IND1",
    "    nombre_corto: \"ejemplo_conceptos\"",
    "    titulo: \"Ejemplo de tabla de conceptos\"",
    "    subtitulo: \"Cada fila es un concepto; las columnas combinan N y %\"",
    "    tipo: tabla_conceptos",
    "    grafico: barras_agrupadas  # opciones: barras_agrupadas, barras_apiladas, barras_horizontales, barras_medias, ninguno",
    "    notas:",
    "      - \"Comentario opcional que aparecerá como nota de tabla.\"",
    "      - \"Se pueden agregar varias notas.\"",
    "",
    "    filas:",
    "      # Cada fila define un 'concepto' y agrupa una o más variables como grupos lógicos.",
    "      # Los nombres de grupo (total, evento, etc.) pueden luego referenciarse como '@total', '@evento' en las columnas.",
    "      - id: concepto_a",
    "        label: \"Concepto A\"",
    "        grupos:",
    "          total:  { vars: [var_a_total] }        # suma simple (p.ej. total de personal)",
    "          evento: { vars: [var_a_evento] }       # variable dicotómica 0/1 (p.ej. capacitados)",
    "",
    "      - id: concepto_b",
    "        label: \"Concepto B\"",
    "        grupos:",
    "          total:  { vars: [var_b_total] }",
    "          evento: { vars: [var_b_evento] }",
    "",
    "    columnas:",
    "      # Ejemplo: total n, n con evento y % con evento",
    "      - id: total_n",
    "        label: \"Total - n\"",
    "        tipo: suma",
    "        var: \"@total\"          # hace referencia al grupo 'total' de cada fila",
    "",
    "      - id: evento_n",
    "        label: \"Evento - n\"",
    "        tipo: suma",
    "        var: \"@evento\"",
    "",
    "      - id: evento_pct",
    "        label: \"Evento - %\"",
    "        tipo: proporcion_rel",
    "        numerador: evento_n",
    "        denominador: total_n",
    "",
    "",
    "  # ------------------------------------------------------------",
    "  # EJEMPLO 2: tabla_conceptos con condiciones sobre códigos",
    "  # ------------------------------------------------------------",
    "  - id: IND2",
    "    nombre_corto: \"ejemplo_condiciones\"",
    "    titulo: \"Ejemplo con condiciones sobre códigos de respuesta\"",
    "    tipo: tabla_conceptos",
    "    grafico: barras_apiladas",
    "    notas:",
    "      - \"Útil cuando una misma variable (select_one) codifica varias categorías (1,2,3,4...).\"",
    "",
    "    filas:",
    "      - id: serv_x",
    "        label: \"Servicio X\"",
    "        grupos:",
    "          resp: { vars: [p001] }   # select_one codificada 1,2,3,4...",
    "      - id: serv_y",
    "        label: \"Servicio Y\"",
    "        grupos:",
    "          resp: { vars: [p002] }",
    "",
    "    columnas:",
    "      # Cada columna aplica una condición distinta sobre la misma variable del grupo '@resp'",
    "      - id: n_cod_1",
    "        label: \"Código 1 - n\"",
    "        tipo: conteo_cond",
    "        var: \"@resp\"",
    "        condicion: \"== 1\"",
    "",
    "      - id: pct_cod_1",
    "        label: \"Código 1 - %\"",
    "        tipo: proporcion_cond",
    "        var: \"@resp\"",
    "        condicion: \"== 1\"",
    "",
    "      - id: n_cod_2",
    "        label: \"Código 2 - n\"",
    "        tipo: conteo_cond",
    "        var: \"@resp\"",
    "        condicion: \"== 2\"",
    "",
    "      - id: pct_cod_2",
    "        label: \"Código 2 - %\"",
    "        tipo: proporcion_cond",
    "        var: \"@resp\"",
    "        condicion: \"== 2\"",
    "",
    "",
    "  # ------------------------------------------------------------",
    "  # EJEMPLO 3: tabla_compuesta (cada fila es una condición distinta)",
    "  # ------------------------------------------------------------",
    "  - id: IND3",
    "    nombre_corto: \"ejemplo_compuesto\"",
    "    titulo: \"Ejemplo de indicador compuesto a partir de varias condiciones\"",
    "    tipo: tabla_compuesta",
    "    grafico: barras_agrupadas",
    "    notas:",
    "      - \"Cada fila corresponde a una expresión lógica evaluada sobre rp_data.\"",
    "      - \"La fila 'total' suele definir el denominador común (p.ej. todos los EESS válidos).\"",
    "",
    "    filas:",
    "      # Cada fila define una condición en términos de variables de rp_data",
    "      - id: cond_a",
    "        label: \"Caso A (var_a == 1)\"",
    "        condicion: \"var_a == 1\"",
    "",
    "      - id: cond_b",
    "        label: \"Caso B (var_b %in% c(1,2))\"",
    "        condicion: \"var_b %in% c(1,2)\"",
    "",
    "      - id: cond_ab",
    "        label: \"Caso A y B\"",
    "        condicion: \"var_a == 1 & var_b %in% c(1,2)\"",
    "",
    "      - id: total",
    "        label: \"Total\"",
    "        condicion: \"valid(var_a, var_b)\"   # helper: al menos una variable con dato válido",
    "",
    "    columnas:",
    "      - id: n",
    "        label: \"n\"",
    "        tipo: conteo_cond_fila    # cuenta ponderada de registros que cumplen la condición de la fila",
    "",
    "      - id: pct",
    "        label: \"%\"",
    "        tipo: proporcion_sobre_total",
    "        referencia_total_fila: \"total\"  # la fila 'total' es el denominador común",
    "",
    "",
    "  # ------------------------------------------------------------",
    "  # EJEMPLO 4: freq_multiple para select_multiple ya dummificada",
    "  # ------------------------------------------------------------",
    "  - id: IND4",
    "    nombre_corto: \"ejemplo_multi\"",
    "    titulo: \"Ejemplo de frecuencias para una pregunta de respuesta múltiple\"",
    "    tipo: freq_multiple",
    "    grafico: barras_horizontales",
    "    notas:",
    "      - \"Se asume que cada dummy es 0/1 y tiene attr(label) con el texto de la opción.\"",
    "      - \"Por ejemplo, p200.1 = 1 si el EESS marcó la primera opción, 0 si no.\"",
    "",
    "    vars:",
    "      - \"p200.1\"    # Opción 1: se toma su label desde rp_data$p200.1",
    "      - \"p200.2\"    # Opción 2",
    "      - \"p200.3\"    # Opción 3",
    "      - \"p200.70\"   # Opción 'Otros' (convención frecuente para 'Otros')",
    "",
    "    usar_labels: true        # lee attr(label) para el nombre de fila",
    "    valor_si: 1              # qué valor se interpreta como \"marcado\"",
    "    incluir_total: true",
    "    total_label: \"Total\"",
    "",
    "",
    "  # ------------------------------------------------------------",
    "  # EJEMPLO 5: freq_multiple de varias select_one en bloque",
    "  # ------------------------------------------------------------",
    "  - id: IND5",
    "    nombre_corto: \"frecuencias_varias\"",
    "    titulo: \"Frecuencias simples de varias preguntas\"",
    "    tipo: freq_multiple",
    "    grafico: ninguno",
    "    notas:",
    "      - \"Útil para agrupar varias tablas de frecuencia simples bajo un mismo indicador.\"",
    "",
    "    vars:",
    "      - id: p010",
    "        label: \"Pregunta P010 (texto resumido)\"",
    "        var: \"p010\"",
    "      - id: p011",
    "        label: \"Pregunta P011 (otra variable)\"",
    "        var: \"p011\"",
    "      - id: p012",
    "        label: \"Pregunta P012\"",
    "        var: \"p012\"",
    "",
    "    opciones:",
    "      incluir_total: true",
    "      total_label: \"Total\"",
    "",
    "",
    "  # ------------------------------------------------------------",
    "  # EJEMPLO 6: tabla_conceptos con medidas numéricas (media, mediana...)",
    "  # ------------------------------------------------------------",
    "  - id: IND6",
    "    nombre_corto: \"medidas_numericas\"",
    "    titulo: \"Ejemplo de promedios, medianas, mínimos y máximos\"",
    "    tipo: tabla_conceptos",
    "    grafico: barras_medias",
    "    notas:",
    "      - \"Pensado para variables numéricas (montos, tiempos, edades, etc.).\"",
    "",
    "    filas:",
    "      - id: grupo_1",
    "        label: \"Grupo 1\"",
    "        grupos:",
    "          valor: { vars: [ingreso_grupo1] }",
    "      - id: grupo_2",
    "        label: \"Grupo 2\"",
    "        grupos:",
    "          valor: { vars: [ingreso_grupo2] }",
    "",
    "    columnas:",
    "      - id: n_dato",
    "        label: \"N con dato\"",
    "        tipo: conteo_cond",
    "        var: \"@valor\"",
    "        condicion: \"no_es_na\"   # helper: x no es NA",
    "",
    "      - id: media",
    "        label: \"Media\"",
    "        tipo: media",
    "        var: \"@valor\"",
    "        condicion: \"no_es_na\"",
    "",
    "      - id: mediana",
    "        label: \"Mediana\"",
    "        tipo: mediana",
    "        var: \"@valor\"",
    "",
    "      - id: minimo",
    "        label: \"Mínimo\"",
    "        tipo: minimo",
    "        var: \"@valor\"",
    "",
    "      - id: maximo",
    "        label: \"Máximo\"",
    "        tipo: maximo",
    "        var: \"@valor\"",
    "",
    "      - id: n_cero",
    "        label: \"N con valor 0\"",
    "        tipo: conteo_cond",
    "        var: \"@valor\"",
    "        condicion: \"== 0\"",
    "",
    "      - id: pct_cero",
    "        label: \"% con valor 0\"",
    "        tipo: proporcion_rel",
    "        numerador: n_cero",
    "        denominador: n_dato",
    "",
    "",
    "  # ------------------------------------------------------------",
    "  # EJEMPLO 7: indicador que usa banderas precomputadas en rp_data",
    "  # ------------------------------------------------------------",
    "  - id: IND7",
    "    nombre_corto: \"banderas_precomputadas\"",
    "    titulo: \"Ejemplo de uso de variables bandera calculadas en R\"",
    "    tipo: tabla_compuesta",
    "    grafico: barras_agrupadas",
    "    notas:",
    "      - \"Las banderas BOOLEANAS (TRUE/FALSE) se calculan previamente en R y se guardan en rp_data.\"",
    "      - \"Por ejemplo: rp_data$flag_condicion_a <- rp_data$var_x == 1 & rp_data$var_y == 2\"",
    "",
    "    filas:",
    "      - id: flag_a",
    "        label: \"Cumple condición A\"",
    "        condicion: \"flag_condicion_a == TRUE\"",
    "",
    "      - id: flag_b",
    "        label: \"Cumple condición B\"",
    "        condicion: \"flag_condicion_b == TRUE\"",
    "",
    "      - id: flag_ab",
    "        label: \"Cumple A y B\"",
    "        condicion: \"flag_condicion_a == TRUE & flag_condicion_b == TRUE\"",
    "",
    "      - id: total",
    "        label: \"Total\"",
    "        condicion: \"valid(flag_condicion_a, flag_condicion_b)\"",
    "",
    "    columnas:",
    "      - id: n",
    "        label: \"n\"",
    "        tipo: conteo_cond_fila",
    "",
    "      - id: pct",
    "        label: \"%\"",
    "        tipo: proporcion_sobre_total",
    "        referencia_total_fila: \"total\"",
    "",
    "",
    "# ===============================================================",
    "# Fin de la plantilla de ejemplo",
    "# A partir de aquí se pueden agregar más indicadores adaptados",
    "# al proyecto real, copiando y modificando los bloques previos.",
    "# ==============================================================="
  )

  writeLines(lines, con = path)
  invisible(path)
}
